//go:build linux && integration

package integration

import (
	"context"
	"encoding/binary"
	"fmt"
	"net"
	"net/netip"
	"os"
	"time"

	"github.com/Realgamer7067/Red_MPUDP/internal/tun"
)

// INTEGRATION-ONLY plaintext packet forwarding (TUN-30). This file is behind
// the `integration` build tag and is never compiled into a release binary;
// production forwarding runs through the encrypted session engine. It exists
// only so the namespace tests can move a cleartext IPv4 packet across a real
// TUN device.

// plaintextPeer is the in-memory endpoint a plaintextForwarder shuttles
// packets to and from.
type plaintextPeer struct {
	fromTUN chan []byte
	toTUN   chan []byte
	// wrote reports the result of every WritePacket the forwarder issues, so a
	// caller can wait for actual receipt by the device instead of sleeping.
	wrote chan error
}

func newPlaintextPeer() *plaintextPeer {
	return &plaintextPeer{
		fromTUN: make(chan []byte, 8),
		toTUN:   make(chan []byte, 8),
		wrote:   make(chan error, 8),
	}
}

// forwardPlaintext reads packets from dev into peer.fromTUN and writes
// peer.toTUN packets back to dev until ctx is done.
func forwardPlaintext(ctx context.Context, dev tun.Device, peer *plaintextPeer) {
	go func() {
		buf := make([]byte, tun.MaxMTU+64)
		for {
			n, err := dev.ReadPacket(ctx, buf)
			if err != nil {
				return
			}
			p := append([]byte(nil), buf[:n]...)
			select {
			case peer.fromTUN <- p:
			case <-ctx.Done():
				return
			}
		}
	}()
	go func() {
		for {
			select {
			case p := <-peer.toTUN:
				_, err := dev.WritePacket(p)
				select {
				case peer.wrote <- err:
				case <-ctx.Done():
					return
				}
				if err != nil {
					return
				}
			case <-ctx.Done():
				return
			}
		}
	}()
}

// tunPlaintextCheck is the "tun-plaintext" helper mode (TUN-26..29). It runs
// inside a namespace: opens red0, verifies it starts at MTU 1180, then proves a
// cleartext IPv4/UDP packet generated by the kernel reaches a TUN reader and
// that a synthetic reply can be written back. Returns a process exit code.
func tunPlaintextCheck() int {
	dev, err := tun.Open(tun.Config{
		Name:    "red0",
		Address: netip.MustParsePrefix("10.80.0.1/24"),
		MTU:     tun.DefaultMTU,
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, "open tun:", err)
		return 1
	}
	defer dev.Close()

	if dev.Name() != "red0" || dev.Index() == 0 {
		fmt.Fprintf(os.Stderr, "unexpected device name=%q index=%d\n", dev.Name(), dev.Index())
		return 1
	}
	if dev.MTU() != tun.DefaultMTU { // TUN-28
		fmt.Fprintf(os.Stderr, "mtu = %d, want %d\n", dev.MTU(), tun.DefaultMTU)
		return 1
	}

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	peer := newPlaintextPeer()
	forwardPlaintext(ctx, dev, peer)

	// The kernel routes 10.80.0.9 on-link out red0; sending a UDP datagram to
	// it makes a real cleartext IPv4/UDP packet appear at the TUN reader.
	conn, err := net.DialUDP("udp", nil, &net.UDPAddr{IP: net.IPv4(10, 80, 0, 9), Port: 7})
	if err != nil {
		fmt.Fprintln(os.Stderr, "dial:", err)
		return 1
	}
	defer conn.Close()
	if _, err := conn.Write([]byte("plaintext-probe")); err != nil {
		fmt.Fprintln(os.Stderr, "write udp:", err)
		return 1
	}

	select {
	case pkt := <-peer.fromTUN: // TUN-29
		if err := checkIPv4UDP(pkt, netip.AddrFrom4([4]byte{10, 80, 0, 9}), 7); err != nil {
			fmt.Fprintln(os.Stderr, "packet check:", err)
			return 1
		}
	case <-ctx.Done():
		fmt.Fprintln(os.Stderr, "no packet reached the TUN reader")
		return 1
	}

	// A synthetic reply can be written back through the device.
	reply := buildIPv4UDP(
		netip.AddrFrom4([4]byte{10, 80, 0, 9}),
		netip.AddrFrom4([4]byte{10, 80, 0, 1}),
		7, uint16(conn.LocalAddr().(*net.UDPAddr).Port),
		[]byte("reply"),
	)
	select {
	case peer.toTUN <- reply:
	case <-ctx.Done():
		fmt.Fprintln(os.Stderr, "could not enqueue reply")
		return 1
	}

	// Wait for the device to actually accept the reply rather than sleeping and
	// hoping. Bounded by the same ctx deadline as everything else here.
	select {
	case err := <-peer.wrote:
		if err != nil {
			fmt.Fprintln(os.Stderr, "write reply to tun:", err)
			return 1
		}
	case <-ctx.Done():
		fmt.Fprintln(os.Stderr, "reply was never written to the tun device")
		return 1
	}

	// Stronger proof for TUN-29: the reply is addressed to this socket, so the
	// kernel must deliver it back up out of red0. Deadline-bounded, and reported
	// separately from the write above so a privileged run says which step broke.
	if err := conn.SetReadDeadline(time.Now().Add(2 * time.Second)); err != nil {
		fmt.Fprintln(os.Stderr, "set read deadline:", err)
		return 1
	}
	rbuf := make([]byte, 64)
	n, err := conn.Read(rbuf)
	if err != nil {
		fmt.Fprintln(os.Stderr, "read reply back from the kernel:", err)
		return 1
	}
	if got := string(rbuf[:n]); got != "reply" {
		fmt.Fprintf(os.Stderr, "reply payload = %q, want %q\n", got, "reply")
		return 1
	}
	return 0
}

func checkIPv4UDP(pkt []byte, wantDst netip.Addr, wantDstPort uint16) error {
	if len(pkt) < 28 {
		return fmt.Errorf("short packet: %d bytes", len(pkt))
	}
	if pkt[0]>>4 != 4 {
		return fmt.Errorf("not IPv4: version nibble %d", pkt[0]>>4)
	}
	ihl := int(pkt[0]&0x0f) * 4
	if ihl < 20 || ihl > len(pkt) {
		return fmt.Errorf("bad IHL %d", ihl)
	}
	total := int(binary.BigEndian.Uint16(pkt[2:4]))
	if total != len(pkt) {
		return fmt.Errorf("total length %d != packet %d", total, len(pkt))
	}
	if pkt[9] != 17 {
		return fmt.Errorf("protocol %d, want UDP(17)", pkt[9])
	}
	dst, _ := netip.AddrFromSlice(pkt[16:20])
	if dst != wantDst {
		return fmt.Errorf("dst %s, want %s", dst, wantDst)
	}
	if dp := binary.BigEndian.Uint16(pkt[ihl+2 : ihl+4]); dp != wantDstPort {
		return fmt.Errorf("dst port %d, want %d", dp, wantDstPort)
	}
	return nil
}

func buildIPv4UDP(src, dst netip.Addr, sport, dport uint16, payload []byte) []byte {
	udpLen := 8 + len(payload)
	total := 20 + udpLen
	p := make([]byte, total)
	p[0] = 0x45
	binary.BigEndian.PutUint16(p[2:4], uint16(total))
	p[8] = 64 // TTL
	p[9] = 17 // UDP
	copy(p[12:16], src.AsSlice())
	copy(p[16:20], dst.AsSlice())
	binary.BigEndian.PutUint16(p[10:12], ipChecksum(p[:20]))
	binary.BigEndian.PutUint16(p[20:22], sport)
	binary.BigEndian.PutUint16(p[22:24], dport)
	binary.BigEndian.PutUint16(p[24:26], uint16(udpLen))
	copy(p[28:], payload)
	return p
}

func ipChecksum(hdr []byte) uint16 {
	var sum uint32
	for i := 0; i+1 < len(hdr); i += 2 {
		sum += uint32(binary.BigEndian.Uint16(hdr[i : i+2]))
	}
	for sum>>16 != 0 {
		sum = (sum & 0xffff) + (sum >> 16)
	}
	return ^uint16(sum)
}
